server:
  port: 8086  # ${PORT:8080}
profile: profile11
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-eureka.asf-demo:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
spring:
  sleuth:
    sampler:
      percentage: 1.0
